name: 'Azure Foundation CI Workflow'

permissions:
      id-token: write
      contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID_PAYG }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID_PAYG }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID_PAYG }}"
  ARM_USE_OIDC: true
  ARM_SKIP_PROVIDER_REGISTRATION: true


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PAYG }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_PAYG }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PAYG }}


      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.1"

      - name: Setup Terragrunt
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.1/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt --version
          terraform --version
  
      - name: 'Init Terraform Backend'
        id: init-terraform-backend
        shell: bash
        run: |
          pushd ../scripts
            # Get Repository ID
            export REPO_ID=$(curl -s -H "Authorization:token ${{ secrets.GIT_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }} | jq '.id')
  
            # Create tf backend if not exists
            chmod +x create-tf-backend-azure.sh
            ./create-tf-backend-azure.sh
          popd
        working-directory: ${{ github.workspace }}/infra  

      - name: Terragrunt Validate
        run: |
          terragrunt run-all validate \
           --terragrunt-working-dir $PWD/env/${{ inputs.environment }}/ \
           --terragrunt-include-external-dependencies \
           --terragrunt-non-interactive
        working-directory: ${{ github.workspace }}/infra  


  
      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terragrunt Plan
        id: tf-plan
        run: |
          export exitcode=0
          terragrunt run-all plan \
          --terragrunt-working-dir $PWD/env/${{ inputs.environment }} \
          -detailed-exitcode \
          -no-color \
          -out tfplan || export exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
  
          find ./env -type f
          bk=$(find ./env -type f -name '*backend.tf')
          cat $bk
          
          if [ $exitcode -eq 1 ]; then
            echo Terragrunt Plan Failed!
            exit 1
          else 
            exit 0
          fi
        working-directory: ${{ github.workspace }}/infra



      #- name: Install Terrascan
      #  run: |
      #    wget https://github.com/tenable/terrascan/releases/download/v1.18.1/terrascan_1.18.1_Linux_x86_64.tar.gz
      #    tar xvzf terrascan_1.18.1_Linux_x86_64.tar.gz
      #    sudo mv terrascan /usr/local/bin/

      #- name: Run Terrascan
      #  run: |
      #   terrascan scan -i terraform -d ./ ts:minseverity=High
      #  env:
      #   TS_ALLOW_DOWNLOADS: "true"
  
      #- name: Install Terraform Linter
      #  run: |
      #   curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      #  shell: bash
   #
      #   
      #- name: Run Terraform Linter
      #  run: |
      #   tflint
      #  env:
      #    TF_VERSION: "1.3.1"
        
         
      # Save plan to artifacts  
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
  